const Constants = {
  //STORE DISPATCHES
  STORE_ACTION_DISPATCH_GRID: "STORE_ACTION_DISPATCH_GRID",
  STORE_ACTION_DISPATCH_CURRENT_DIRECTION:
    "STORE_ACTION_DISPATCH_CURRENT_DIRECTION",
  STORE_ACTION_DISPATCH_FORM_FIELD_UPDATE:
    "STORE_ACTION_DISPATCH_FORM_FIELD_UPDATE",
  STORE_ACTION_DISPATCH_FORM_ROBOT_PLACE:
    "STORE_ACTION_DISPATCH_FORM_ROBOT_PLACE",
  STORE_ACTION_DISPATCH_FORM_OUTPUT: "STORE_ACTION_DISPATCH_FORM_OUTPUT",
  STORE_ACTION_DISPATCH_FORM_ROBOT_EXISTENSE:
    "STORE_ACTION_DISPATCH_FORM_ROBOT_EXISTENSE",

  //ROBOT VALID DIRECTIONS
  ROBOT_DIRECTION_NORTH: "NORTH",
  ROBOT_DIRECTION_SOUTH: "SOUTH",
  ROBOT_DIRECTION_EAST: "EAST",
  ROBOT_DIRECTION_WEST: "WEST",

  //ROTATION
  ROBOT_ROTATION_LEFT: "LEFT",
  ROBOT_ROTATION_RIGHT: "RIGHT",

  //X,Y,F input
  FORM_X_INPUT: "x_input",
  FORM_Y_INPUT: "y_input",
  FORM_F_INPUT: "f_input",
};

export default Constants;
